name: "Simple Python HTTP Server"
version: "1.0.1"
slug: "simple_python_http"
description: "A simple Python HTTP server for Home Assistant"
url: "https://github.com/Ahmed9190/simple-python-http"
arch:
  - aarch64
  - amd64
  - armv7
init: false
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:web
ports:
  8099/tcp: 8099
homeassistant: "2022.12.0"
options:
  port: 8099
  message: "Hello from Home Assistant Add-on!"
schema:
  port: port
  message: str
